# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20160414_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
